#!/bin/bash
#SBATCH --ntasks=16
#SBATCH --mem-per-cpu=300
#SBATCH -J LTX-Li-E
#SBATCH --time=1:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=amaan@pppl.gov

time mpiexec -np $SLURM_NTASKS python3 thickness_wMPI.py
